# Generated by Django 3.1.1 on 2020-09-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='diagonal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Диагональ'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='display_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип дисплея'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='processor_freq',
            field=models.CharField(blank=True, max_length=255, verbose_name='Частота процессора'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='ram',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='time_without_charge',
            field=models.CharField(blank=True, max_length=255, verbose_name='Время работы аккумулятора'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='video',
            field=models.CharField(blank=True, max_length=255, verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='accum_volume',
            field=models.CharField(blank=True, max_length=255, verbose_name='Объем батареи'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='diagonal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Диагональ'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='display_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип дисплея'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='front_cam',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фронтальная камера'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='main_cam',
            field=models.CharField(blank=True, max_length=255, verbose_name='Передняя камера'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='resolution',
            field=models.CharField(blank=True, max_length=255, verbose_name='Разрешение экрана'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='SD карта'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume',
            field=models.CharField(blank=True, max_length=255, verbose_name='Макс. объём встраиваемой памяти'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
