# Generated by Django 3.1.1 on 2020-10-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200929_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='in_order',
        ),
    ]
