# Generated by Django 3.1.1 on 2020-10-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20201015_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='front_cam',
            new_name='front_cam_mp',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='main_cam',
            new_name='main_cam_mp',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='sd_volume',
            new_name='sd_volume_max',
        ),
    ]
