# Generated by Django 3.1.1 on 2020-10-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20201016_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='front_cam_mp',
            new_name='front_cam',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='main_cam_mp',
            new_name='main_cam',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='sd_volume_max',
            new_name='sd_volume',
        ),
    ]
