# Generated by Django 3.1.1 on 2020-10-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_sliders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sliders',
        ),
    ]
